use pem;
show tables;
# 1) DDL (data definition language) \ work with structure of data
# DRCAT 
# DROP, RENAME, CREATE,ALTER,TRUNCATE
CREATE TABLE IF NOT EXISTS occupation(
name char(20), age int, gender char(10));
show tables;
desc occupation;
ALTER TABLE OCCUPATION ADD CITY VARCHAR(20);
DESC OCCUPATION;
ALTER TABLE OCCUPATION CHANGE CITY PLACE VARCHAR(20);
ALTER TABLE OCCUPATION DROP PLACE;
DESC OCCUPATION;
ALTER TABLE OCCUPATION MODIFY COLUMN GENDER VARCHAR(10);
ALTER TABLE OCCUPATION RENAME TO PARTICIPANTS;
DESC OCCUPATION; # ERROR AS OCCUPATION TABLE HAS RENAME TO PARTICIPANTS
DESC PARTICIPANTS;
DROP TABLE PARTICIPANTS;
SHOW TABLES;
TRUNCATE CUSTOMERS;
SELECT * FROM CUSTOMERS;
DESC CUSTOMERS;


## 2) DML DATA MANIPULATION LANGUAGES (WORK WITH THE CONTENTS OF THE TABLE)
# 1)INSERT VALUES FOR ALL THE COLUMNS IN THE TABLE
INSERT INTO CUSTOMERS VALUES (1, 'PEMA', 'MALE', '1993-12-07');
ALTER TABLE CUSTOMERS MODIFY GENDER VARCHAR(10); # WAS GETTING ERROR AS VARVHAR(5) BEFORE
SELECT * FROM CUSTOMERS;

# INSERT VALUES FOR SPECIFIC COLUMNS IN THE TABLE
INSERT INTO CUSTOMERS (CID, CNAME) VALUES(2,'TASHI');

# INSERT MULTIPLE RECORDS
INSERT INTO CUSTOMERS VALUES (3,'TSEWANG','MALE','1994-12-01'),(4,'YOUNTEN','MALE','1992-5-6'),(5,'PHUNTSOK','MALE','1992-08-15');
SELECT * FROM CUSTOMERS;



# 2)DELETE COMMAND : DELETE A RECORD FROM THE TABLE
DELETE FROM CUSTOMERS WHERE CID = 2;
SET SQL_SAFE_UPDATES = 0; # IF WE DIDNT SET THIS WE WILL GET ERROR! ITS IN SAFE MODE
SELECT * FROM CUSTOMERS;

# DELETE ALL RECORDS FROM THE TABLE
DELETE FROM CUSTOMERS;
SELECT * FROM CUSTOMERS;


INSERT INTO CUSTOMERS VALUES (1,'PEMA','MALE','1993-12-07'),
(2,'TSEWANG','MALE','1994-05-10'),
(3,'YOUNTEN','MALE','1992-06-05'),
(4,'PHUNTSOK','MALE','1992-1-08');
SELECT * FROM CUSTOMERS;

# 3) UPDATE COMMAND: MAKE CHANGES TO RECORD
# a) UPDATE A RECORD IN THE TABLE
UPDATE CUSTOMERS SET GENDER = 'FEMALE',DOB= '1993-12-07' WHERE CNAME='PHUNTSOK';
SELECT * FROM CUSTOMERS;

# b) UPDATE ALL RECORDS IN THE TABLE
UPDATE CUSTOMERS SET DOB= '1993-12-07' , GENDER= 'MALE', CNAME='PEMA';
SELECT * FROM CUSTOMERS;
# UPDATE ALL THE RECORDS INTO SAME NAME, SAME DOB, AND GENDER